Location-Challenge
netpulse/BookingClasses pull request #22
Opened 2024-02-08 22:27 UTC by JulioAMarin

2024-02-13 11:40 UTC, anamnizami commented on package.json
Failed to resolve dependency on npm install. 
<img width="1512" alt="image" src="https://github.com/egym/mwa-reference/assets/118906364/f79a60ed-20a3-4f8a-9eb3-9e11554226db">

2024-02-13 11:40 UTC, anamnizami commented on package.json
after force installing the dependencies using 
`npm i --force `
app throws following error on 
`npm start`
<img width="824" alt="image" src="https://github.com/egym/mwa-reference/assets/118906364/bfa9866d-a39b-46e9-afa5-1eff2c909e16">
<img width="856" alt="image" src="https://github.com/egym/mwa-reference/assets/118906364/08cacc3f-3c5b-44d7-80f9-ec4b69aaebe9">


and `npm run ios`.

<img width="1049" alt="image" src="https://github.com/egym/mwa-reference/assets/118906364/0241f3bf-a5d8-4fc7-abec-f38e9fa271db">

2024-02-13 11:40 UTC, anamnizami commented on package.json
we were unable to verify UI changes because of this error. you can review the changes in the packages and version and try to work with the existing version. If upgrading the package is necessary in your opinion please make sure to update the corresponding packages too to resolve peer dependency.

2024-02-13 11:40 UTC, anamnizami commented on package.json
> +    "react-scripts": "5.0.1",
we are using vite, so react-scripts is redundant here.

2024-02-13 11:40 UTC, anamnizami commented on public/index.html
I suppose you were running the app with react-scripts, see the previous comment and index should be in root, check vite documentation for further clarity.

2024-02-13 11:40 UTC, anamnizami commented on capacitor.config.json
> +{}
we already have capacitor.config.ts so this file is redundant.

2024-02-13 11:40 UTC, anamnizami commented on public/mockServiceWorker.js
it also seems to be related with react-scripts.

2024-02-13 11:40 UTC, anamnizami commented on src/components/SearchBar/SearchBar.tsx
> +const SearchBar = ({ onSearch }: Search) => {
it is recommended to use FC types for components, also props name can be more clear like SearchBarProps.

2024-02-13 11:40 UTC, anamnizami commented on src/components/SearchBar/SearchBar.tsx
> +  const handleSearch = (event: any) => {
instead of any you can use types from the IonSearchbar.

2024-02-13 11:40 UTC, anamnizami commented on src/components/SearchBar/SearchBar.tsx
> +  const [searchText, setSearchText] = useState('');
state is redundant here, as it is handled by IonSearchbar and therefore this whole component is not required.

2024-02-13 11:40 UTC, anamnizami commented on src/components/SearchBar/SearchBar.tsx
> +  return <IonSearchbar value={searchText} onIonChange={handleSearch} placeholder="Search by location" />;
placeholder is not localised.

2024-02-13 11:40 UTC, anamnizami commented on src/hooks/useLocations/useLocations.ts
> +  const res = await fetch('https://egymidp.netpulse.com/np/company/children');
did you open the application on emulator and was it working? We have a createApiRequest helper to handle http calls.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +  // @ts-ignore
how would you resolve it?

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/hooks/useLocation.ts
> +  const groupedLocations = useMemo(() => {
why did you name this groupedLocations?

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/hooks/useLocation.ts
> +const useLocation = (): UseLocationResultProps => {
confusing name of the hook.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/hooks/useLocation.ts
seems like a redundant hook.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +import '../LocationItem.css';
we use scss modules.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +  const [locationResult, setLocationResult] = useState<Location>();
this is redundant, you can use useMemo instead of this state and useEffect below.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +          <IonSegment onIonChange={(e) => setSelectedSegment(e.detail.value as ClassType)} value={selectedSegment}>
it would be better for readability if you would move handler to separate function.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +          {loading ? (
nested ternary operators are the bad practice.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationHours/LocationHours.tsx
> +  const amPmFormat = (hour24: string) => {
1. This function should be moved out of component scope as it doesn't have any dependencies from react.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationInfo/LocationInfo.tsx
> +const LocationInfo: FC<LocationProp> = ({ location }: LocationProp) => {
suggestion: you can create the array structure of icon and label iterate over that to render the list.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationInfo/LocationInfo.tsx
> +          <p>Not Information Found</p>
it is not localised.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationItem.css
we are using scss modules.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationItem.css
> +.ion-text-micro-wrap {
.ion-* classes are reserved and used by ionic and we can import directly from ionic and shouldn't redefine them.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/Locations.tsx
pattern is not followed. you can view the src/pages/Geolocation to see how we are separating and structuring code.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/Locations.tsx
> +import './LocationItem.css';
we are using scss modules.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationItem.tsx
Name of the component is confusing as this component renders lists.

2024-02-13 11:40 UTC, anamnizami commented on src/pages/Locations/LocationItem.tsx
> +              <IonItem className="custom-item" detail={false} routerLink={`/locations/${eachLocation.uuid}`} button>
router link doesn't use the link from route urls mwa-reference/src/utils/constants/router.ts

2024-02-23 09:36 UTC, AlexKolomiytsev requested changes

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/hooks/useLocations/LocationsPageProps.ts
wrong usage. LocationPageProps.ts should be related only to the LocationPage component, i.e. it should be placed inside src/pages/Locations/LocationsPage

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationsPageContainer.tsx
this file must be inside src/pages/Locations/LocationsPage

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationsPageContainer.tsx
> +  const result = useLocations();
```
const result = useLocationsPage();
```

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationsPageContainer.tsx
> +import useLocations from 'src/hooks/useLocations';
```
import useLocationsPage from 'src/hooks/useLocationsPage';
```

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/router.ts
> +import Locations from './Locations';
import LocationsPage from './LocationsPage';

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/router.ts
> +import LocationDetail from './Locations/LocationDetail';
import LocationDetailPage from './Locations/LocationDetailPage';

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/styles/Locations.scss
error on `npm start`
scss module should have a specific name pattern `Locations.module.scss`
![image (8)](https://github.com/egym/mwa-reference/assets/15348910/4bfa5fbc-8497-43d4-9c00-9aefaef263ea)

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/index.tsx
redundant file

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationsPage/hooks/useLocationsPage.ts
> +const useLocationsPage = (initialLocations: Location[]) => {
this hook should be used at the LocationPageContainer level
it should not receive anything in arguments

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationsPage/LocationsPage.tsx
> +  const { locationResult, handleSearch } = useLocationsPage(locationList);
`useLocationsPage` should be called inside LocationsPageContainer

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/hooks/useLocations/useLocations.ts
> +const useLocations = (): LocationsPageProps => {
remove this hook, no need for extra wrapper around locationsQuery

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/hooks/useLocations/useLocations.ts
> +const useLocationQuery = () => {
rename to `useLocations`

then use can use it like this:

```
const { locationsQuery } = useLocations();

```

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationSegment/LocationSegment.tsx
> +        <LocationInfo locationFeed={transformLocationFeed(location)} />
not a way how React should work

instead you should 
- pass location as a Location type inside LocationInfo
- remove transformLocationFeed in LocationSegment, move it to LocationInfo and use useMemo

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/hooks/useLocationDetail.ts
> +import type { LocationsDetailProps } from 'src/hooks/useLocations/LocationsPageProps';
LocationDetailsPage should use it's own LocationDetailsPageProps file

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/LocationDetailContainer.tsx
> +  const { locationId } = useParams<LocationQueryParam>();
useParams should go inside `useLocationDetailPage`

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/LocationDetailContainer.tsx
> +  return <>{result.loading ? <Loader /> : <LocationDetail {...result} />}</>;
no conditions/logic should be inside `*Container` components
Container is only for bounding hook (logic) and component (presentation)

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/LocationDetailContainer.tsx
> +  return <>{result.loading ? <Loader /> : <LocationDetail {...result} />}</>;
the same logic you have inside src/pages/Locations/LocationDetail/LocationDetail:33

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +  const onSegmentChange = (e: IonSegmentCustomEvent<SegmentChangeEventDetail>) => {
function should go to `useLocationDetailsPage`

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +  const [selectedSegment, setSelectedSegment] = useState<LocationSegmentType>(LocationSegmentType.Location);
state should go to `useLocationsDetailsPage`

2024-02-23 09:36 UTC, AlexKolomiytsev commented on src/pages/Locations/LocationDetail/LocationDetail.tsx
> +import type { LocationsDetailProps } from 'src/hooks/useLocations/LocationsPageProps';
types shpuld go from it's own types file - LocationDetailsPageProps

2024-03-06 14:54 UTC, closed without merging